### ISSUE TITLE
[CLIENT] User CRUD (by Saturday)

### ISSUE THREAD

**Issue by thePaulista** [kristindiannefoss/pivot#44]

**Comment by kristindiannefoss** [comment]
Need donor, recipient(local admin), global admin.  May need to rethink this, our namespacing for recipient, the way we have cart set up is more like the way a donor will interact with the site.

**Comment by kristindiannefoss** [comment]
Update, edit, delete, 
All users should be able to do this to their own 
Admin should be able to do it for all users.

**Comment by JaredRoth** [comment]
Does "users" here refer to donors or recipients?

**Comment by kristindiannefoss** [comment]
All users as far as I understand, I'm in the process of doing this card, did you also start it?
