### ISSUE TITLE
[INTERNAL] Unit test Cart

### ISSUE THREAD

**Issue by thePaulista** [kristindiannefoss/pivot#69]

**Comment by thePaulista** [comment]
Cart.new({}).add_need(need, need_type.max) is failing.  it passes regardless of how many needs are getting passed in. slack sent to jared.

**Comment by thePaulista** [comment]
need to do a update and delete test.

**Comment by JaredRoth** [comment]
It's an old comment at this point, but I don't see anywhere that the snippet I sent you is used. It will fix that problem.

**Comment by thePaulista** [comment]
jared, i had a bad git issue late in the evening with one of my PRs, and so
instead of trying to figure out how to reset the head on my local branch,
it was easier just to close the PR, and abandon that branch, and do a new
one.  but yes, i haven't submitted that test yet.  it's commited, but not
pushed.  i'm going to try and do a jumbo commit with the model tests
tomorrow when a group mate is nearby so that the code review  and merge can
happen faster.
